
import java.awt.Dimension;
import java.awt.Toolkit;
import java.util.Calendar;
import java.util.Date;
import javax.swing.JOptionPane;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author Dell
 */
public class rent extends javax.swing.JFrame {
    
    
    /**
     * Creates new form rent
     */
    public rent() {
        initComponents();
        // make the window in the center screen
        Toolkit toolkit = getToolkit();
        Dimension size = toolkit.getScreenSize();
        setLocation(size.width/2 - getWidth()/2, size.height/2 - getHeight()/2); 
        
        // get the customer id and search its details then set it to custNameTextField and custPhoneTextField
        String cust_idStr = custComboBox.getSelectedItem().toString(); 
        cust_id = Integer.parseInt(cust_idStr);
        DataHandler.getCustDetails(cust_id);
        custNameTextField.setText(cust_name);
        custPhoneTextField.setText(String.valueOf(cust_phone));
        
        // get the equipment id and search its details then set it to equipNameTextField, equipPriceTextField and availableTextField
        String equip_idStr = equipComboBox.getSelectedItem().toString(); 
        equip_id = Integer.parseInt(equip_idStr);
        DataHandler.getEquipDetails(equip_id);
        equipNameTextField.setText(equip_name);
        equipPriceTextField.setText(String.valueOf(equip_price));
        availableTextField.setText(String.valueOf(quantity));
       
        // set the date of rent_start to today
        rent_start = new Date();
        rentStartDate.setDate(rent_start);
        
        // add 1 day to the current date and set that date as the minimum selectable date for returning the equipment
        Calendar cal = Calendar.getInstance(); 
        cal.add(Calendar.DAY_OF_MONTH, 1);
        returnRentDate.setMinSelectableDate(cal.getTime());
        returnRentDate.setDate(cal.getTime());
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton3 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        custNameTextField = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        custPhoneTextField = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        equipComboBox = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        equipNameTextField = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        equipPriceTextField = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        rentStartDate = new com.toedter.calendar.JDateChooser();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        returnRentDate = new com.toedter.calendar.JDateChooser();
        jLabel10 = new javax.swing.JLabel();
        totalLabel = new javax.swing.JLabel();
        rentButton = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();
        homeButton = new javax.swing.JButton();
        custComboBox = new javax.swing.JComboBox<>();
        quantityTextField = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        availableTextField = new javax.swing.JTextField();

        jButton3.setText("jButton3");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jLabel1.setText("Customer ID:");

        jLabel2.setText("Customer Name:");

        custNameTextField.setEditable(false);
        custNameTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                custNameTextFieldActionPerformed(evt);
            }
        });

        jLabel3.setText("Customer Phone:");

        custPhoneTextField.setEditable(false);

        jLabel4.setText("Equipment ID:");

        equipComboBox.setModel(new javax.swing.DefaultComboBoxModel(DataHandler.getEquipment()));
        equipComboBox.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                equipComboBoxItemStateChanged(evt);
            }
        });

        jLabel5.setText("Equipment Name:");

        equipNameTextField.setEditable(false);

        jLabel6.setText("Equipment Price:");

        equipPriceTextField.setEditable(false);

        jLabel7.setText("Quantity:");

        rentStartDate.setEnabled(false);

        jLabel8.setText("Rent Date:");

        jLabel9.setText("Return Date:");

        returnRentDate.addInputMethodListener(new java.awt.event.InputMethodListener() {
            public void caretPositionChanged(java.awt.event.InputMethodEvent evt) {
            }
            public void inputMethodTextChanged(java.awt.event.InputMethodEvent evt) {
                returnRentDateInputMethodTextChanged(evt);
            }
        });
        returnRentDate.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                returnRentDatePropertyChange(evt);
            }
        });

        jLabel10.setText("Total Price:");

        totalLabel.setText("0.00");

        rentButton.setText("Rent");
        rentButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rentButtonActionPerformed(evt);
            }
        });

        jLabel12.setFont(new java.awt.Font("Segoe UI Light", 1, 36)); // NOI18N
        jLabel12.setText("RENT");

        homeButton.setText("Home");
        homeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                homeButtonActionPerformed(evt);
            }
        });

        custComboBox.setModel(new javax.swing.DefaultComboBoxModel(DataHandler.getCustomer()));
        custComboBox.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                custComboBoxItemStateChanged(evt);
            }
        });

        quantityTextField.setText("1");

        jLabel11.setText("Available:");

        availableTextField.setEditable(false);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel1))
                                .addGap(22, 22, 22)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(custNameTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 95, Short.MAX_VALUE)
                                    .addComponent(custComboBox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(45, 45, 45))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel7)
                                    .addComponent(jLabel8)
                                    .addComponent(jLabel9))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(rentStartDate, javax.swing.GroupLayout.DEFAULT_SIZE, 125, Short.MAX_VALUE)
                                            .addComponent(returnRentDate, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                            .addComponent(quantityTextField)
                                            .addComponent(custPhoneTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 97, Short.MAX_VALUE))
                                        .addGap(0, 0, Short.MAX_VALUE)))))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addGap(32, 32, 32)
                                .addComponent(equipComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel5)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(equipNameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(jLabel10)
                                            .addComponent(jLabel11))
                                        .addGap(18, 18, 18)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(equipPriceTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 99, Short.MAX_VALUE)
                                            .addComponent(totalLabel)
                                            .addComponent(availableTextField)))
                                    .addComponent(rentButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addContainerGap(13, Short.MAX_VALUE))))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(homeButton)
                        .addGap(118, 118, 118)
                        .addComponent(jLabel12)
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel12)
                    .addComponent(homeButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 21, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(custComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(custNameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(custPhoneTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(equipComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(equipNameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(equipPriceTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(availableTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(9, 9, 9)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel10)
                            .addComponent(totalLabel))
                        .addGap(36, 36, 36)
                        .addComponent(rentButton))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(5, 5, 5)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel7)
                                    .addComponent(quantityTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel8))
                            .addComponent(rentStartDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel9))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGap(2, 2, 2)
                                .addComponent(returnRentDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGap(28, 28, 28))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void custNameTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_custNameTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_custNameTextFieldActionPerformed

    private void custComboBoxItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_custComboBoxItemStateChanged
        // TODO add your handling code here:
        // get the customer id and search its details then set it to custNameTextField and custPhoneTextField
        String cust_idStr = custComboBox.getSelectedItem().toString(); 
        cust_id = Integer.parseInt(cust_idStr);
        DataHandler.getCustDetails(cust_id);
        custNameTextField.setText(cust_name);
        custPhoneTextField.setText(String.valueOf(cust_phone));
        
        
    }//GEN-LAST:event_custComboBoxItemStateChanged

    private void equipComboBoxItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_equipComboBoxItemStateChanged
        // TODO add your handling code here:
        // get the equipment id and search its details then set it to equipNameTextField, equipPriceTextField and availableTextField
        String equip_idStr = equipComboBox.getSelectedItem().toString(); 
        equip_id = Integer.parseInt(equip_idStr);
        DataHandler.getEquipDetails(equip_id);
        equipNameTextField.setText(equip_name);
        equipPriceTextField.setText(String.valueOf(equip_price));
        availableTextField.setText(String.valueOf(quantity));
        
    }//GEN-LAST:event_equipComboBoxItemStateChanged

    private void rentButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rentButtonActionPerformed
        // TODO add your handling code here:
          //java.sql.Date sqldate = new java.sql.Date(jDateChooser3.getDate().getTime());
          //java.sql.Date sqldate = new java.sql.Date(jDateChooser3.getDate().getTime());
        try { 
            Date rent_end; // create a variable date
        
            // get the string quantity and convert it to integer
            String quan = quantityTextField.getText();
            int rentQuantity = Integer.parseInt(quan);
                
            // check if the quantity thats being asked to rent is more than the available quantity
            if(rentQuantity>quantity){
                JOptionPane.showMessageDialog(null, "Please enter less than the quantity available"); 
            } else{
                // if the quantity thats being asked to rent is less than the available,
                rent_end = new Date(returnRentDate.getDate().getTime()); // get the return date
                int duration =DataHandler.getDateDiff(rent_start,rent_end); // get the difference in days of rent_start and rent_end
                double total = equip_price * duration * rentQuantity; // compute for the total price
                totalLabel.setText(total+""); // assign the total price in the label
                DataHandler.addRent(cust_id, rent_start, rent_end, rentQuantity, equip_id, total);} // call the function addRent and pass these variables cust_id, rent_start, rent_end, rentQuantity, equip_id, total 
            } catch (Exception ex){
                JOptionPane.showMessageDialog(null, "Invalid input!"); // if the user inputted characters, instead of integers, display the error
            } 
    }//GEN-LAST:event_rentButtonActionPerformed

    private void returnRentDatePropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_returnRentDatePropertyChange
        // TODO add your handling code here:
        
       
    }//GEN-LAST:event_returnRentDatePropertyChange

    private void returnRentDateInputMethodTextChanged(java.awt.event.InputMethodEvent evt) {//GEN-FIRST:event_returnRentDateInputMethodTextChanged
        // TODO add your handling code here:
        
    }//GEN-LAST:event_returnRentDateInputMethodTextChanged

    private void homeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_homeButtonActionPerformed
        // TODO add your handling code here:
        this.setVisible(false); // hide this window
    }//GEN-LAST:event_homeButtonActionPerformed
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(rent.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(rent.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(rent.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(rent.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new rent().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField availableTextField;
    private javax.swing.JComboBox<String> custComboBox;
    private javax.swing.JTextField custNameTextField;
    private javax.swing.JTextField custPhoneTextField;
    private javax.swing.JComboBox<String> equipComboBox;
    private javax.swing.JTextField equipNameTextField;
    private javax.swing.JTextField equipPriceTextField;
    private javax.swing.JButton homeButton;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField quantityTextField;
    private javax.swing.JButton rentButton;
    private com.toedter.calendar.JDateChooser rentStartDate;
    private com.toedter.calendar.JDateChooser returnRentDate;
    private javax.swing.JLabel totalLabel;
    // End of variables declaration//GEN-END:variables
    public static String cust_name="";
    public static int cust_phone=0;
    public static int cust_id=0;
    public static int equip_id=0;
    public static String equip_name="";
    public static double equip_price=0;
    public static Date rent_start;
    public static int quantity=0;
}
