

import java.awt.Dimension;
import java.awt.Toolkit;
import java.util.Date;
import java.sql.Timestamp;
import javax.swing.JOptionPane;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author Dell
 */
public class return_equipment extends javax.swing.JFrame {
    /**
     * Creates new form return_equipment
     */
    public return_equipment() {
        initComponents();
        // make the window in the center screen
        Toolkit toolkit = getToolkit();
        Dimension size = toolkit.getScreenSize();
        setLocation(size.width/2 - getWidth()/2, size.height/2 - getHeight()/2);
        
        // get the rent id and search its details then set it to custNameTextField and equipNameTextField
        rent_idStr = rentComboBox.getSelectedItem().toString(); 
        rent_id = Integer.parseInt(rent_idStr);
        DataHandler.getRentDetails(rent_id);
        custNameTextField.setText(cust_name);
        equipNameTextField.setText(equip_name);
        
        // set the minimum selectable date to return_date and set it as the returnDate
        returnedDate.setMinSelectableDate(return_date);
        returnedDate.setDate(return_date);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        rentComboBox = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        custNameTextField = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        equipNameTextField = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        returnedDate = new com.toedter.calendar.JDateChooser();
        returnButton = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        homeButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        rentComboBox.setModel(new javax.swing.DefaultComboBoxModel(DataHandler.getRent()));
        rentComboBox.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                rentComboBoxItemStateChanged(evt);
            }
        });
        rentComboBox.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                rentComboBoxPropertyChange(evt);
            }
        });

        jLabel1.setText("Rent ID:");

        custNameTextField.setEditable(false);

        jLabel2.setText("Customer Name:");

        jLabel3.setText("Equipment Name:");

        equipNameTextField.setEditable(false);

        jLabel4.setText("Return Date:");

        returnedDate.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                returnedDatePropertyChange(evt);
            }
        });

        returnButton.setText("Return");
        returnButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                returnButtonActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Segoe UI Light", 1, 36)); // NOI18N
        jLabel6.setText("RETURN");

        homeButton.setText("Home");
        homeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                homeButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel1)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel4))
                                .addGap(28, 28, 28)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(custNameTextField)
                                    .addComponent(equipNameTextField)
                                    .addComponent(returnedDate, javax.swing.GroupLayout.DEFAULT_SIZE, 147, Short.MAX_VALUE)
                                    .addComponent(rentComboBox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                            .addComponent(returnButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(homeButton)
                        .addGap(20, 217, Short.MAX_VALUE))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel6)
                .addGap(80, 80, 80))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(homeButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 13, Short.MAX_VALUE)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(rentComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(custNameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel3)
                    .addComponent(equipNameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(42, 42, 42)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel4)
                    .addComponent(returnedDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addComponent(returnButton)
                .addGap(29, 29, 29))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void rentComboBoxPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_rentComboBoxPropertyChange
        // TODO add your handling code here:
        
    }//GEN-LAST:event_rentComboBoxPropertyChange

    private void rentComboBoxItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_rentComboBoxItemStateChanged
        // TODO add your handling code here:
        // get the rent id and search its details then set it to custNameTextField and equipNameTextField
        rent_idStr = rentComboBox.getSelectedItem().toString(); 
        rent_id = Integer.parseInt(rent_idStr);
        DataHandler.getRentDetails(rent_id);
        custNameTextField.setText(cust_name);
        equipNameTextField.setText(equip_name);
        
        // set the minimum selectable date to return_date and set it as the returnDate
        returnedDate.setMinSelectableDate(return_date);
        returnedDate.setDate(return_date);
        
    }//GEN-LAST:event_rentComboBoxItemStateChanged

    private void returnedDatePropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_returnedDatePropertyChange
   
    }//GEN-LAST:event_returnedDatePropertyChange

    private void returnButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_returnButtonActionPerformed
        // TODO add your handling code here:
        // convert the return date to timestamp and get the difference between return date and returned date
        int duration =DataHandler.getDateDiff(return_date,(new Timestamp(returnedDate.getDate().getTime()))); 
        // compute for the fine
        int fine = duration * price;
        if(fine<0){ // if the fine is less than 0, set it to 0 (this only happens if the customer returns the equipment day/s before the return date)
            fine = 0;
        } 
        // call the return equipment and pass the variables
        DataHandler.returnEquipment(equip_id, rent_id, fine, new Timestamp(returnedDate.getDate().getTime()),quantity);
        JOptionPane.showMessageDialog(null, "Thank you for returning, you have a FINE of "+fine+" Euro");
       
    }//GEN-LAST:event_returnButtonActionPerformed

    private void homeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_homeButtonActionPerformed
        // TODO add your handling code here:
        this.setVisible(false); // hide this window
    }//GEN-LAST:event_homeButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(return_equipment.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(return_equipment.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(return_equipment.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(return_equipment.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new return_equipment().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField custNameTextField;
    private javax.swing.JTextField equipNameTextField;
    private javax.swing.JButton homeButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JComboBox<String> rentComboBox;
    private javax.swing.JButton returnButton;
    private com.toedter.calendar.JDateChooser returnedDate;
    // End of variables declaration//GEN-END:variables
    public static int rent_id=0;
    public static String rent_idStr="";
    public static String equip_name="";
    public static int equip_id=0;
    public static double equip_price=0;
    public static String cust_name="";
    public static Date return_date;
    public static int price = 1;
    public static Date currentDate = new Date();
    public static int quantity = 0;
}
